title: "CodeContact"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2324S1-CS2103T-T09-2"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
